# ------------------------
# Step 1: Build react app
# ------------------------
FROM node:20 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json  ./
RUN yarn

# Copy the rest of the project files and build
COPY . ./

RUN cp .env.dev .env

RUN yarn run build:prod

# ------------------------
# Step 2: Serve with Nginx
# ------------------------
FROM nginx:alpine

# Copy the build output to nginx's default static file serving directory
COPY --from=builder /app/build /usr/share/nginx/html

# Copy the custom nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the default nginx port
EXPOSE 80

# Start nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]